# Generated by Django 2.2.6 on 2019-10-28 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('balance', models.IntegerField(default=10000)),
                ('accountid', models.IntegerField(default=3, primary_key=True, serialize=False, unique=True)),
                ('owner_type', models.PositiveSmallIntegerField(choices=[(1, 'individual'), (2, 'Commercial')])),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('C', 'Commercial'), ('P', 'Premium'), ('E', 'Enterprize')], max_length=1),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'User_Approved'), ('R', 'Rejected'), ('P', 'In_Process'), ('S', 'Successful')], editable=False, max_length=1)),
                ('amount', models.IntegerField(default=0)),
                ('ttype', models.CharField(blank=True, choices=[('C', 'Credit'), ('D', 'Debit'), ('T', 'Transfer')], editable=False, max_length=1)),
                ('transaction_time', models.DateTimeField(auto_now=True)),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_account', to='accounts.Account')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_account', to='accounts.Account')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('transaction_time', models.DateTimeField(auto_now=True)),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_account1', to='accounts.Account')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='accounts.UserProfile'),
        ),
    ]
