# Generated by Django 2.2.6 on 2019-10-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191028_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('A', 'User_Approved'), ('R', 'Rejected'), ('PI', 'In_Process'), ('S', 'Successful')], editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ttype',
            field=models.CharField(blank=True, choices=[('CR', 'Credit'), ('D', 'Debit'), ('T', 'Transfer')], editable=False, max_length=1),
        ),
    ]
