# Generated by Django 2.2.6 on 2019-10-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191028_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_type',
            new_name='role',
        ),
    ]
